//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources
{
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessage
    {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessage()
        {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager
        {
            get
            {
                if (object.ReferenceEquals(resourceMan, null))
                {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.ExceptionMessage", typeof(ExceptionMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture
        {
            get
            {
                return resourceCulture;
            }
            set
            {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to ExceedMaxFileSize.
        /// </summary>
        public static string ExceedMaxFileSize
        {
            get
            {
                return ResourceManager.GetString("ExceedMaxFileSize", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to FileNotExist.
        /// </summary>
        public static string FileNotExist
        {
            get
            {
                return ResourceManager.GetString("FileNotExist", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to LockedUser.
        /// </summary>
        public static string LockedUser
        {
            get
            {
                return ResourceManager.GetString("LockedUser", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to MissingData.
        /// </summary>
        public static string MissingData
        {
            get
            {
                return ResourceManager.GetString("MissingData", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to NotSupportedMediaType.
        /// </summary>
        public static string NotSupportedMediaType
        {
            get
            {
                return ResourceManager.GetString("NotSupportedMediaType", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Unauthorized.
        /// </summary>
        public static string Unauthorized
        {
            get
            {
                return ResourceManager.GetString("Unauthorized", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to UnHandledException.
        /// </summary>
        public static string UnHandledException
        {
            get
            {
                return ResourceManager.GetString("UnHandledException", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Company name is required..
        /// </summary>
        public static string CompanyNameRequired
        {
            get
            {
                return ResourceManager.GetString("CompanyNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Email is required..
        /// </summary>
        public static string EmailRequired
        {
            get
            {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Username is required..
        /// </summary>
        public static string UsernameRequired
        {
            get
            {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Password is required..
        /// </summary>
        public static string PasswordRequired
        {
            get
            {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Full name is required..
        /// </summary>
        public static string FullNameRequired
        {
            get
            {
                return ResourceManager.GetString("FullNameRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to National ID is required..
        /// </summary>
        public static string NationalIdRequired
        {
            get
            {
                return ResourceManager.GetString("NationalIdRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to National ID must be 14 digits..
        /// </summary>
        public static string NationalIdInvalidLength
        {
            get
            {
                return ResourceManager.GetString("NationalIdInvalidLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Phone number is required..
        /// </summary>
        public static string PhoneRequired
        {
            get
            {
                return ResourceManager.GetString("PhoneRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Phone number must be between 7 and 15 digits..
        /// </summary>
        public static string PhoneInvalidLength
        {
            get
            {
                return ResourceManager.GetString("PhoneInvalidLength", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insured person is required..
        /// </summary>
        public static string InsuranceCompanyPersonRequired
        {
            get
            {
                return ResourceManager.GetString("InsuranceCompanyPersonRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Plate number is required..
        /// </summary>
        public static string PlateNumberRequired
        {
            get
            {
                return ResourceManager.GetString("PlateNumberRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Make is required..
        /// </summary>
        public static string MakeRequired
        {
            get
            {
                return ResourceManager.GetString("MakeRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Model is required..
        /// </summary>
        public static string ModelRequired
        {
            get
            {
                return ResourceManager.GetString("ModelRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Company name (English) is required..
        /// </summary>
        public static string CompanyNameEnRequired
        {
            get
            {
                return ResourceManager.GetString("CompanyNameEnRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Company name (Arabic) is required..
        /// </summary>
        public static string CompanyNameArRequired
        {
            get
            {
                return ResourceManager.GetString("CompanyNameArRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Company is required..
        /// </summary>
        public static string CompanyIdRequired
        {
            get
            {
                return ResourceManager.GetString("CompanyIdRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Account not found..
        /// </summary>
        public static string AccountNotFound
        {
            get
            {
                return ResourceManager.GetString("AccountNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Incorrect username or password..
        /// </summary>
        public static string IncorrectUsernameOrPassword
        {
            get
            {
                return ResourceManager.GetString("IncorrectUsernameOrPassword", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to A user with this username already exists..
        /// </summary>
        public static string UsernameAlreadyExists
        {
            get
            {
                return ResourceManager.GetString("UsernameAlreadyExists", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insurance company not found..
        /// </summary>
        public static string InsuranceCompanyNotFound
        {
            get
            {
                return ResourceManager.GetString("InsuranceCompanyNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Insurance company person not found or does not belong to this company..
        /// </summary>
        public static string InsuranceCompanyPersonNotFound
        {
            get
            {
                return ResourceManager.GetString("InsuranceCompanyPersonNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Data request not found..
        /// </summary>
        public static string DataRequestNotFound
        {
            get
            {
                return ResourceManager.GetString("DataRequestNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User creation failed..
        /// </summary>
        public static string UserCreationFailed
        {
            get
            {
                return ResourceManager.GetString("UserCreationFailed", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User creation failed: {0}.
        /// </summary>
        public static string UserCreationIdentityErrors
        {
            get
            {
                return ResourceManager.GetString("UserCreationIdentityErrors", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registration request not found..
        /// </summary>
        public static string RegistrationRequestNotFound
        {
            get
            {
                return ResourceManager.GetString("RegistrationRequestNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Main participant ticket not found..
        /// </summary>
        public static string RegistrationMainParticipantTicketNotFound
        {
            get
            {
                return ResourceManager.GetString("RegistrationMainParticipantTicketNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Main participant ticket not approved..
        /// </summary>
        public static string RegistrationMainParticipantTicketNotApproved
        {
            get
            {
                return ResourceManager.GetString("RegistrationMainParticipantTicketNotApproved", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Name is required..
        /// </summary>
        public static string RegistrationNameNotSent
        {
            get
            {
                return ResourceManager.GetString("RegistrationNameNotSent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Position is required..
        /// </summary>
        public static string RegistrationPositionNotSent
        {
            get
            {
                return ResourceManager.GetString("RegistrationPositionNotSent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ticket fees are required..
        /// </summary>
        public static string RegistrationTicketFeesNotSent
        {
            get
            {
                return ResourceManager.GetString("RegistrationTicketFeesNotSent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Currency is required..
        /// </summary>
        public static string RegistrationCurrencyNotSent
        {
            get
            {
                return ResourceManager.GetString("RegistrationCurrencyNotSent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Title is required..
        /// </summary>
        public static string RegistrationTitleRequired
        {
            get
            {
                return ResourceManager.GetString("RegistrationTitleRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Nationality is required..
        /// </summary>
        public static string RegistrationNationalityRequired
        {
            get
            {
                return ResourceManager.GetString("RegistrationNationalityRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ticket type is required..
        /// </summary>
        public static string RegistrationTicketTypeNotSent
        {
            get
            {
                return ResourceManager.GetString("RegistrationTicketTypeNotSent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to National ID or passport number is required..
        /// </summary>
        public static string RegistrationNationalIdOrPassportRequired
        {
            get
            {
                return ResourceManager.GetString("RegistrationNationalIdOrPassportRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to National ID attachment is required..
        /// </summary>
        public static string RegistrationNationalIdAttachmentRequired
        {
            get
            {
                return ResourceManager.GetString("RegistrationNationalIdAttachmentRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Passport attachment is required..
        /// </summary>
        public static string RegistrationPassportAttachmentRequired
        {
            get
            {
                return ResourceManager.GetString("RegistrationPassportAttachmentRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Spouse identity documents must be different from the main participant..
        /// </summary>
        public static string RegistrationSpouseIdentityMustDiffer
        {
            get
            {
                return ResourceManager.GetString("RegistrationSpouseIdentityMustDiffer", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refund amount is not correct..
        /// </summary>
        public static string RegistrationRefundAmountIncorrect
        {
            get
            {
                return ResourceManager.GetString("RegistrationRefundAmountIncorrect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Refund reason is required..
        /// </summary>
        public static string RegistrationRefundReasonRequired
        {
            get
            {
                return ResourceManager.GetString("RegistrationRefundReasonRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Please cancel or refund the spouse ticket first..
        /// </summary>
        public static string RegistrationCancelSpouseTicketFirst
        {
            get
            {
                return ResourceManager.GetString("RegistrationCancelSpouseTicketFirst", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total amount after discount is not correct..
        /// </summary>
        public static string RegistrationTotalAfterDiscountIncorrect
        {
            get
            {
                return ResourceManager.GetString("RegistrationTotalAfterDiscountIncorrect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total amount is not correct..
        /// </summary>
        public static string RegistrationTotalAmountIncorrect
        {
            get
            {
                return ResourceManager.GetString("RegistrationTotalAmountIncorrect", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User category is required..
        /// </summary>
        public static string RegistrationUserCategoryNotSent
        {
            get
            {
                return ResourceManager.GetString("RegistrationUserCategoryNotSent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Payment method is required..
        /// </summary>
        public static string RegistrationPaymentMethodNotSent
        {
            get
            {
                return ResourceManager.GetString("RegistrationPaymentMethodNotSent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The request does not have a main participant ticket..
        /// </summary>
        public static string RegistrationRequestMissingMainParticipantTicket
        {
            get
            {
                return ResourceManager.GetString("RegistrationRequestMissingMainParticipantTicket", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ticket status must not be cancelled, rejected, or refunded..
        /// </summary>
        public static string RegistrationTicketInvalidStatusForOperation
        {
            get
            {
                return ResourceManager.GetString("RegistrationTicketInvalidStatusForOperation", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registration request ticket not found..
        /// </summary>
        public static string RegistrationRequestTicketNotFound
        {
            get
            {
                return ResourceManager.GetString("RegistrationRequestTicketNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Ticket not found..
        /// </summary>
        public static string RegistrationTicketNotFound
        {
            get
            {
                return ResourceManager.GetString("RegistrationTicketNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Terms and conditions must be accepted..
        /// </summary>
        public static string RegistrationTermsNotAccepted
        {
            get
            {
                return ResourceManager.GetString("RegistrationTermsNotAccepted", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Total amount is required..
        /// </summary>
        public static string RegistrationTotalAmountNotSent
        {
            get
            {
                return ResourceManager.GetString("RegistrationTotalAmountNotSent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Payment currency is required..
        /// </summary>
        public static string RegistrationPaymentCurrencyNotSent
        {
            get
            {
                return ResourceManager.GetString("RegistrationPaymentCurrencyNotSent", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Country is required..
        /// </summary>
        public static string RegistrationCountryRequired
        {
            get
            {
                return ResourceManager.GetString("RegistrationCountryRequired", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Main participant must reopen first..
        /// </summary>
        public static string RegistrationMainParticipantMustReopenFirst
        {
            get
            {
                return ResourceManager.GetString("RegistrationMainParticipantMustReopenFirst", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Registration request ticket must be cancelled or rejected..
        /// </summary>
        public static string RegistrationTicketMustBeCancelledOrRejected
        {
            get
            {
                return ResourceManager.GetString("RegistrationTicketMustBeCancelledOrRejected", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invalid user category..
        /// </summary>
        public static string RegistrationInvalidUserCategory
        {
            get
            {
                return ResourceManager.GetString("RegistrationInvalidUserCategory", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        public static string UserNotFound
        {
            get
            {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Agenda item was not found..
        /// </summary>
        public static string CommitteeAgendaItemNotFound
        {
            get
            {
                return ResourceManager.GetString("CommitteeAgendaItemNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Invite was not found..
        /// </summary>
        public static string CommitteeInviteNotFound
        {
            get
            {
                return ResourceManager.GetString("CommitteeInviteNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Committee was not found..
        /// </summary>
        public static string CommitteeNotFound
        {
            get
            {
                return ResourceManager.GetString("CommitteeNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Committee session was not found..
        /// </summary>
        public static string CommitteeSessionNotFound
        {
            get
            {
                return ResourceManager.GetString("CommitteeSessionNotFound", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Member is already assigned to this committee..
        /// </summary>
        public static string CommitteeMemberAlreadyAssigned
        {
            get
            {
                return ResourceManager.GetString("CommitteeMemberAlreadyAssigned", resourceCulture);
            }
        }

        public static string UserNotExsists
        {
            get
            {
                return ResourceManager.GetString("UserNotExsists", resourceCulture);
            }
        }

        public static string OtpEmailFormatNotValid
        {
            get
            {
                return ResourceManager.GetString("OtpEmailFormatNotValid", resourceCulture);
            }
        }

        public static string OtpEmailNotFound
        {
            get
            {
                return ResourceManager.GetString("OtpEmailNotFound", resourceCulture);
            }
        }

        public static string OtpNotValidEmailOrOtp
        {
            get
            {
                return ResourceManager.GetString("OtpNotValidEmailOrOtp", resourceCulture);
            }
        }

        public static string OtpEmailSendFailed
        {
            get
            {
                return ResourceManager.GetString("OtpEmailSendFailed", resourceCulture);
            }
        }
    }
}
